### ISSUE TITLE
feature request - spherical globe support

### ISSUE THREAD

**Issue by johndpope** [dataminr/DTMHeatmap#3]
I am using another library whirlyglobe 
it has a quad tile class MaplyQuadImageTilesLayer  that requests x / y / z  for tiles. 

There's a sample project here
https://github.com/GeographicaGS/MeetUp_Python_Jan2016/blob/d016266d5b0ef97076d1367f6d5ac1986b10ffcf/code/globe-ios/MeetUP/MeetUP/ViewController.m

I want to merge this library with that one but am stuck....
![ooidx](https://cloud.githubusercontent.com/assets/289994/15328791/245aee74-1c24-11e6-9d86-61c20ecb5a25.png)

The existing code I understand throws a layer on top of map. 

I want to generate a uiimage for a given tile.  
(A tile consists of a lower left / upper right lat / long bounds.)

I guess I could create a mkmaprect and pass it to these functions.
Can you see any scaling problems in particular core graphics with this approach? 

- (NSDictionary *)mapPointsWithHeatInMapRect:(MKMapRect)rect
                                     atScale:(MKZoomScale)scale

Renderer -> 
- (void)drawMapRect:(MKMapRect)mapRect
          zoomScale:(MKZoomScale)zoomScale
          inContext:(CGContextRef)context

**Comment by bryanoltman** [comment]
This seems like a pretty tall order. The limitation will likely not be CoreGraphics, but the fact that this project integrates _very_ tightly with MapKit, and it doesn't appear that WhirlyGlobe-Maply uses MapKit at all. That said, the logic behind creating the heatmap is fairly straightforward, so you could probably base your own on the code in DTMHeatmapRenderer.m. There are also a couple repositories mentioned in the readme that will generate an image based on heat data, but afaik none of them are meant to be used on a sphere. Best of luck!
